import fs from 'node:fs'
import path from 'node:path'
import { loadOpenApi, operationParameters, runContractChecks } from './openapi-utils.js'

const document = loadOpenApi()
const result = runContractChecks(document)
if (result.failures.length > 0) {
  console.error(result.failures.map((failure) => `- ${failure}`).join('\n'))
  process.exit(1)
}

const outputDirectory = path.resolve('shared/generated')
fs.mkdirSync(outputDirectory, { recursive: true })

const operations = result.operations.map((record) => {
  const parameters = operationParameters(document, record)
  const browserManagedHeaders = parameters
    .filter((parameter) => parameter?.in === 'header' && parameter.name.toLowerCase() === 'origin')
    .map((parameter) => parameter.name)
  const declaredHeaders = parameters
    .filter((parameter) => parameter?.in === 'header' && parameter.required === true)
    .map((parameter) => parameter.name)
  const securityHeaders = (record.operation.security ?? []).flatMap((requirement) =>
    Object.keys(requirement).flatMap((schemeName) => {
      const scheme = document.components?.securitySchemes?.[schemeName]
      return scheme?.type === 'http' && scheme.scheme?.toLowerCase() === 'bearer' ? ['Authorization'] : []
    }),
  )
  return {
    operationId: record.operation.operationId,
    method: record.method.toUpperCase(),
    path: record.route,
    requiredHeaders: [...new Set([...declaredHeaders, ...securityHeaders])].filter(
      (header) => !browserManagedHeaders.some((managed) => managed.toLowerCase() === header.toLowerCase()),
    ),
    browserManagedHeaders,
    pathParams: parameters
      .filter((parameter) => parameter?.in === 'path' && parameter.required === true)
      .map((parameter) => parameter.name),
  }
})

const clientFunctions = operations
  .map(
    ({ operationId }) => `    ${operationId}: (init = {}) => requestOperation('${operationId}', init, clientOptions),`,
  )
  .join('\n')

const clientSource = `// Generated by npm run contract:generate. Do not edit by hand.

const operations = ${JSON.stringify(operations, null, 2)}

function resolvePath(pathTemplate, pathParams = {}) {
  return pathTemplate.replaceAll(/\\{([^}]+)\\}/g, (_, name) => {
    const value = pathParams[name]
    if (value === undefined || value === null) throw new Error('Missing path parameter: ' + name)
    return encodeURIComponent(String(value))
  })
}

function hasHeader(headers, name) {
  return Object.entries(headers).some(([key, value]) => key.toLowerCase() === name.toLowerCase() && value !== undefined && value !== null && String(value).length > 0)
}

async function requestOperation(operationId, init = {}, defaults = {}) {
  const operation = operations.find((candidate) => candidate.operationId === operationId)
  if (!operation) throw new Error('Unknown API operation: ' + operationId)
  const baseUrl = init.baseUrl ?? defaults.baseUrl ?? (typeof window === 'undefined' ? 'http://localhost:3000' : window.location.origin)
  const path = resolvePath(operation.path, init.pathParams)
  const url = new URL(path, baseUrl)
  const fetchImpl = init.fetchImpl ?? defaults.fetchImpl ?? globalThis.fetch
  if (typeof fetchImpl !== 'function') throw new Error('fetch implementation is required')
  const headers = { ...(defaults.headers ?? {}), ...(init.headers ?? {}) }
  for (const requiredHeader of operation.requiredHeaders) {
    if (!hasHeader(headers, requiredHeader)) throw new Error('Missing required header: ' + requiredHeader)
  }
  const requestInit = { ...init, method: operation.method, headers }
  delete requestInit.baseUrl
  delete requestInit.fetchImpl
  delete requestInit.pathParams
  return fetchImpl(url, requestInit).then(async (response) => {
    const payload = await response.json().catch(() => undefined)
    if (!response.ok) {
      const error = new Error(payload?.error?.message ?? 'API request failed')
      error.status = response.status
      error.code = payload?.error?.code
      error.requestId = payload?.error?.requestId
      throw error
    }
    return payload
  })
}

/** @returns {Record<string, (init?: object) => Promise<object>>} */
export function createApiClient(clientOptions = {}) {
  return {
${clientFunctions}
  }
}

export { operations }
`

const schemaSource = `// Generated by npm run contract:generate. Do not edit by hand.

export const openApiDocument = ${JSON.stringify(document, null, 2)}
`

fs.writeFileSync(path.join(outputDirectory, 'api-client.js'), clientSource)
fs.writeFileSync(path.join(outputDirectory, 'api-schema.js'), schemaSource)
console.log(`Generated ${operations.length} operations into shared/generated/`)
